import turtle

haylie = turtle.Turtle()
screen = turtle.Screen()

haylie.speed(100)

screen.bgcolor("lightblue")

haylie.penup()
haylie.goto(-300, -500)
haylie.pendown()

haylie.color("brown")

haylie.begin_fill()
haylie.forward(300)
haylie.left(120)
haylie.forward(300)
haylie.left(120)
haylie.forward(300)
haylie.end_fill()

haylie.color("brown")

haylie.begin_fill()
haylie.left(30)
haylie.forward(200)
haylie.left(90)
haylie.forward(300)
haylie.left(90)
haylie.forward(200)
haylie.left(90)
haylie.forward(200)
haylie.left(90)
haylie.end_fill()

haylie.penup()
haylie.goto(600, -600)
haylie.pendown()

haylie.color("gray")

haylie.begin_fill()
haylie.forward(100)
haylie.right(90)
haylie.forward(600)
haylie.right(90)
haylie.forward(100)
haylie.right(90)
haylie.forward(600)
haylie.right(90)
haylie.forward(100)
haylie.end_fill()


haylie.penup()
haylie.goto(-200, -500)
haylie.pendown()

haylie.color("lightblue")

haylie.begin_fill()
haylie.forward(100)
haylie.left(90)
haylie.forward(100)
haylie.left(90)
haylie.forward(100)
haylie.left(90)
haylie.forward(100)
haylie.left(90)
haylie.end_fill()

haylie.color("gray")


haylie.begin_fill()
haylie.left(90)
haylie.forward(45)
haylie.right(90)
haylie.forward(50)
haylie.right(90)
haylie.forward(45)
haylie.left(90)
haylie.forward(10)
haylie.left(90)
haylie.forward(45)
haylie.right(90)
haylie.forward(40)
haylie.left(90)
haylie.forward(10)
haylie.left(90)
haylie.forward(40)
haylie.right(90)
haylie.forward(45)
haylie.left(90)
haylie.forward(10)
haylie.left(90)
haylie.forward(45)
haylie.right(90)
haylie.forward(50)
haylie.right(90)
haylie.forward(10)
haylie.end_fill()
haylie.forward(135)
haylie.right(180)
haylie.forward(300)

haylie.color("green")

haylie.begin_fill()
haylie.penup()
haylie.goto(-400, -700)
haylie.pendown()
haylie.right(180)
haylie.forward(1500)
haylie.right(90)
haylie.forward(500)
haylie.right(90)
haylie.forward(1500)
haylie.right(90)
haylie.forward(500)
haylie.end_fill()